
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    command:
      [
        "sh",
        "-c",
        "npm install && npm run build && node dist/app.js"
      ]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
